### ISSUE TITLE
"loosen bound" commit not yet pushed to hackage

### ISSUE THREAD

**Issue by theSuess** [raymoo/NEET#5]
Hey there,

Forgive me if I'm just stupid but I'm trying to use your library and can't because cabal still says it requires base < 4.8 (current 4.8.2.0). This should have been fixed in the "losen bounds" commit. I'm not familiar with publishing packages to hackage but it seems like you need to push the updates or something.

**Comment by raymoo** [comment]
Done, sorry for not doing this earlier. The version I just uploaded (0.4.0.1) should have the looser bounds.
